### ISSUE TITLE
Possibility to skip a single test

### ISSUE THREAD

**Issue by ControlTheBit** [AStepaniuk/qunit-parameterize#9]
We need the possibility to skip a single test / data set, so that it somehow is possible e.g. to skip test A in the following example and not the whole dataset.

> QUnit
>     .cases([
>         { a : 2, b : 2, expectedSum : 4 }, // <--- this is test A
>         { a : 5, b : 5, expectedSum : 10 },
>         { a : 40, b : 2, expectedSum : 42 }
>     ])
>     .test("Sum test", function(params) {
>         var actualSum = sum(params.a, params.b);
>         equal(actualSum, params.expectedSum);
>     });

**Comment by AStepaniuk** [comment]
Hi,

Thanks for suggestion. Any ideas how would syntax look for marking particular test case skipped?

**Comment by AStepaniuk** [comment]
I presume this method should be used internally:
http://api.qunitjs.com/QUnit.skip/

**Comment by ControlTheBit** [comment]
Yes, that is true, http://api.qunitjs.com/QUnit.skip/ should be called internally.
I haven't thought about a proper syntax for this yet, but what about something like this?

> QUnit.cases([
QUnit.skip({ a : 2, b : 2, expectedSum : 4 }), // <--- this is will be skipped A
{ a : 5, b : 5, expectedSum : 10 },
{ a : 40, b : 2, expectedSum : 42 }
])

**Comment by marek629** [comment]
Hi, I think that a simple _skip_ boolean parameter (false by default) in _cases_ objects will be a good option.

For example:

```javascript
QUnit.cases([
    {
        title: 'skip me',
        skip: true,
        a: 2, b: 2, expectedSum: 4
    }
])
```

It is much clear and easy, isn't it?

**Comment by AStepaniuk** [comment]
Hi, yeah, the idea with `skip` parameter looks good.

I'm just a little worried that it might break backward compatibility for some existing tests. I.e. when there already was specified `skip` parameter as a usual parameter.

To decrease the impact for the existing tests, I guess it worth to use parameter `_skip`.

**Comment by marek629** [comment]
Hey!
Hm... I don't think that `skip` parameter is in popular use now but name of the parameter is no problem for me. As you wish - it can call `_skip`.
I'm implementing my version of the fix on the repo fork. I will send pull request on finish.

**Comment by marek629** [comment]
Hey @AStepaniuk, what is a status of the pull request. Do you have any suggestions?

**Comment by AStepaniuk** [comment]
@marek629 's pull request is merged into master. Now this issue can be closed as completed.
